# Copyright Takeshi Yonezu. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:
  node:
    image: arm32v7/${IROHA_IMG}
    ports:
      - "50051:50051"
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    depends_on:
      - redis
      - postgres

  postgres:
    image: arm32v7/postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - IROHA_POSTGRES_PASSWORD=HelloW0rld
    depends_on:
      - redis

  redis:
    image: arm32v7/redis

volumes:
  ccache-data:
